# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23186181e3b1ac222885c225d7a799c1179be7ce338ebf097d3d030d7a8220df7c4d0a4e27de31a25801ee80e6eea11572d2ebee849a07518a72e219b3613c63

test:
  secret_key_base: a7196164184fd5546c575766f7f12bc7183efce2228b657f87e0ba8468270f77b87cf10429bdf845077cf0af0eb91bf7a8f54a86e32e5e2c827060db33a435de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
